name: Daily + PR security scan

permissions:
  contents: read
  security-events: write

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 02:00 UTC
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  osv-scan:
    name: Run OSV Scanner and Upload SARIF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OSV Scanner (current code)
        uses: google/osv-scanner-action/osv-scanner-action@v2.0.2
        with:
          scan-args: |-
            --output=osv-head.sarif
            --format=sarif
            ./app
        continue-on-error: true

      - name: Checkout base branch
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.base_ref }}
          git checkout origin/${{ github.base_ref }}
          cp -r ./ ./base-code

      - name: Run OSV Scanner (base code)
        if: github.event_name == 'pull_request'
        working-directory: ./base
        uses: google/osv-scanner-action/osv-scanner-action@v2.0.2
        with:
          scan-args: |-
            --output=osv-base.sarif
            --format=sarif
            ./app
        continue-on-error: true

      - name: Compare OSV results (reporter)
        if: github.event_name == 'pull_request'
        uses: google/osv-scanner-action/osv-reporter-action@main
        with:
          scan-args: |-
            --output=osv-diff.sarif
            --new=osv-head.sarif
            --old=./base-code/osv-base.sarif
            --gh-annotations=false
            --fail-on-vuln=false

      - name: Upload SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: |
            ${{ github.event_name == 'pull_request' && 'osv-diff.sarif' || 'osv-head.sarif' }}

      - name: Upload OSV diff report as artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: osv-diff-report
          path: osv-diff.sarif
          retention-days: 7

  semgrep:
    name: Run Semgrep and Upload SARIF
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep with Java ruleset
        run: |
          semgrep scan --config=p/java --sarif --output=semgrep.sarif

      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
