name: Daily security scan

permissions:
  security-events: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 02:00 UTC
  workflow_dispatch:

jobs:
  osv-scan:
    name: Run OSV Scanner and Upload SARIF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Run scanner"
        uses: google/osv-scanner-action/osv-scanner-action@8dded7155905cd666190a12dc9997000e58d163d # v2.0.
        with:
          scan-args: |-
            --output=scan.sarif
            --format=sarif
            ./app
        continue-on-error: true
      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@28deaeda66b76a05916b6923827895f2b14ab387
        with:
          sarif_file: scan.sarif

  semgrep:
      name: Semgrep run
      runs-on: ubuntu-latest

      container:
        image: returntocorp/semgrep

      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Run Semgrep with Java ruleset
          run: |
            semgrep scan --config=p/java --sarif --output=semgrep.sarif
  
        - name: Upload Semgrep SARIF to GitHub Security Dashboard
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: semgrep.sarif
