name: Daily security scan

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 02:00 UTC
  workflow_dispatch:

jobs:
  osv-scan:
    name: Run OSV Scanner and Upload SARIF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OSV Scanner
        uses: google/osv-scanner-action@v2.0.2
        with:
          scan-args: |-
            --output=osv.scanner.sarif
            --format=sarif
            "./app"

      - name: Upload SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: osv-scanner.sarif
