name: Daily security scan

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 02:00 UTC
  workflow_dispatch:

jobs:
  osv-scan:
    name: Run OSV Scanner and Upload SARIF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Run scanner"
        uses: google/osv-scanner/actions/scanner@main
        with:
          scan-args: |-
            --output=scan.sarif
            --format=sarif
            -r ./app
        continue-on-error: true
      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@28deaeda66b76a05916b6923827895f2b14ab387
        with:
          sarif_file: scan.sarif
